language: c
dist: xenial
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bison
    - flex
    - autoconf
    - automake
    - gcc-8
    - libtool-bin
    - make
    - sparse
    - wget
    - libibumad-dev
script:
  - scripts/travis-checkpatch
  - scripts/travis-build
